func throwingFunc() throws {
    return
}
do {
try throwingFunc()
} catch {
<#code#>
}
